fix

diff --git a/.github/workflows/fleet-model-test.yml b/.github/workflows/fleet-model-test.yml
--- a/.github/workflows/fleet-model-test.yml
+++ b/.github/workflows/fleet-model-test.yml
@@ -68,55 +68,55 @@ jobs:
           fi
           echo "is_md_only: $(cat $GITHUB_OUTPUT | grep is_md_only || echo '未找到')"
     
-  # integration-test-H20-single-card:
-  #   needs: check_documents_type
-  #   if: ${{ needs.check_documents_type.outputs.is_md_only == 'false' }}
-  #   name: Integration test (H20, single card)
-  #   runs-on:
-  #     group: Fleet-H-single-card
-  #   env:
-  #     PIP_CACHE_DIR: /home/.cache/pip
-  #     CACHE_DIR: /home/.cache
-  #     TASK: formers-fleet-CI-${{ github.event.pull_request.number }}-integration-test-single-card
-  #   steps:
-  #     - name: Determine the runner
-  #       run: |
-  #         gpu_id=$(( $(echo $PWD | awk -F'/' '{print $3}' | awk -F'-' '{print $2}') + 3 ))
-  #         echo GPU_DEVICES="$gpu_id" >> $GITHUB_ENV
+  integration-test-H20-single-card:
+    needs: check_documents_type
+    if: ${{ needs.check_documents_type.outputs.is_md_only == 'false' }}
+    name: Integration test (H20, single card)
+    runs-on:
+      group: Fleet-H-single-card
+    env:
+      PIP_CACHE_DIR: /home/.cache/pip
+      CACHE_DIR: /home/.cache
+      TASK: formers-fleet-CI-${{ github.event.pull_request.number }}-integration-test-single-card
+    steps:
+      - name: Determine the runner
+        run: |
+          gpu_id=$(( $(echo $PWD | awk -F'/' '{print $3}' | awk -F'-' '{print $2}') + 3 ))
+          echo GPU_DEVICES="$gpu_id" >> $GITHUB_ENV
 
-  #     - name: Check docker image and run container
-  #       env:
-  #         GPU_DEVICES: ${{ env.GPU_DEVICES }}
-  #       run: |
-  #         container_name=${TASK}-$(date +%Y%m%d-%H%M%S)
-  #         echo "container_name=${container_name}" >> ${{ github.env }}
-  #         docker pull $docker_image
-  #         set -x
-  #         docker run -d -t --name ${container_name} --gpus "\"device=${GPU_DEVICES}\"" --shm-size=32G \
-  #           -v "/dev/shm:/dev/shm"  \
-  #           -v ${{ github.workspace }}/../../..:${{ github.workspace }}/../../.. \
-  #           -v ${{ github.workspace }}/../../..:/root \
-  #           -v /ssd1/paddle-1/action_cache:/home/.cache \
-  #           -v ${{ github.workspace }}:/workspace \
-  #           -e BRANCH \
-  #           -e PR_ID \
-  #           -e COMMIT_ID \
-  #           -e PADDLE_ROOT \
-  #           -e ci_scripts \
-  #           -e CACHE_DIR \
-  #           -e no_proxy \
-  #           -e CI_name \
-  #           -e PIP_CACHE_DIR \
-  #           -e GITHUB_SHA="${{ github.event.pull_request.head.sha }}" \
-  #           -e GITHUB_HEAD_REF="${{ github.head_ref }}" \
-  #           -e GITHUB_BASE_SHA="${{ github.event.pull_request.base.sha }}" \
-  #           -e GITHUB_REPO_NAME="${{ github.repository }}" \
-  #           -e GITHUB_EVENT_NAME="${{ github.event_name }}" \
-  #           -e GITHUB_EVENT_PULL_REQUEST_NUMBER="${{ github.event.pull_request.number }}" \
-  #           -e GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
-  #           -e GITHUB_RUN_ID="${{ github.run_id }}" \
-  #           -e PR_USER="${{ github.event.pull_request.user.login }}" \
-  #           -w /workspace --network host ${docker_image}
+      - name: Check docker image and run container
+        env:
+          GPU_DEVICES: ${{ env.GPU_DEVICES }}
+        run: |
+          container_name=${TASK}-$(date +%Y%m%d-%H%M%S)
+          echo "container_name=${container_name}" >> ${{ github.env }}
+          docker pull $docker_image
+          set -x
+          docker run -d -t --name ${container_name} --gpus "\"device=${GPU_DEVICES}\"" --shm-size=32G \
+            -v "/dev/shm:/dev/shm"  \
+            -v ${{ github.workspace }}/../../..:${{ github.workspace }}/../../.. \
+            -v ${{ github.workspace }}/../../..:/root \
+            -v /ssd1/paddle-1/action_cache:/home/.cache \
+            -v ${{ github.workspace }}:/workspace \
+            -e BRANCH \
+            -e PR_ID \
+            -e COMMIT_ID \
+            -e PADDLE_ROOT \
+            -e ci_scripts \
+            -e CACHE_DIR \
+            -e no_proxy \
+            -e CI_name \
+            -e PIP_CACHE_DIR \
+            -e GITHUB_SHA="${{ github.event.pull_request.head.sha }}" \
+            -e GITHUB_HEAD_REF="${{ github.head_ref }}" \
+            -e GITHUB_BASE_SHA="${{ github.event.pull_request.base.sha }}" \
+            -e GITHUB_REPO_NAME="${{ github.repository }}" \
+            -e GITHUB_EVENT_NAME="${{ github.event_name }}" \
+            -e GITHUB_EVENT_PULL_REQUEST_NUMBER="${{ github.event.pull_request.number }}" \
+            -e GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
+            -e GITHUB_RUN_ID="${{ github.run_id }}" \
+            -e PR_USER="${{ github.event.pull_request.user.login }}" \
+            -w /workspace --network host ${docker_image}
 
       - name: Install PaddleFormers
         id: formers_install
@@ -206,71 +206,71 @@ jobs:
   #         fi
   #         '
 
-  #     - name: Qwen3-vl-8k-single-card
-  #       if: (success() || failure()) && steps.formers_install.conclusion == 'success'
-  #       run: |
-  #         docker exec -t ${{ env.container_name }} /bin/bash -ce '
-  #         source /root/proxy
-  #         timeout 5m bash -x PaddleFormers/tests/integration_test/qwen3vl_sft_single_card.sh single
-  #         exit_code=$?
-  #         if [[ "$exit_code" != "0" ]]; then
-  #           echo -e "::error:: \033[31mIntegration test failed: Qwen3-vl-8k-single-card.\033[0m"
-  #           exit 1
-  #         else
-  #           echo -e "\033[32mIntegration test succeeded: Qwen3-vl-8k-single-card.\033[0m"
-  #         fi
-  #         '
+      - name: Qwen3-vl-8k-single-card
+        if: (success() || failure()) && steps.formers_install.conclusion == 'success'
+        run: |
+          docker exec -t ${{ env.container_name }} /bin/bash -ce '
+          source /root/proxy
+          timeout 5m bash -x PaddleFormers/tests/integration_test/qwen3vl_sft_single_card.sh single
+          exit_code=$?
+          if [[ "$exit_code" != "0" ]]; then
+            echo -e "::error:: \033[31mIntegration test failed: Qwen3-vl-8k-single-card.\033[0m"
+            exit 1
+          else
+            echo -e "\033[32mIntegration test succeeded: Qwen3-vl-8k-single-card.\033[0m"
+          fi
+          '
 
 
-  #     - name: Terminate and delete the container
-  #       if: ${{ always() }}
-  #       run: |
-  #         set +e
-  #         docker exec -t ${{ env.container_name }} /bin/bash -c 'rm -rf * .[^.]*'
-  #         docker rm -f ${{ env.container_name }}
+      - name: Terminate and delete the container
+        if: ${{ always() }}
+        run: |
+          set +e
+          docker exec -t ${{ env.container_name }} /bin/bash -c 'rm -rf * .[^.]*'
+          docker rm -f ${{ env.container_name }}
 
 
-  # integration-test-H20-multi-card:
-  #   needs: check_documents_type
-  #   if: ${{ needs.check_documents_type.outputs.is_md_only == 'false' }}
-  #   name: Integration test (H20, multi-card)
-  #   runs-on:
-  #     group: Fleet-H-multi-card
-  #   env:
-  #     PIP_CACHE_DIR: /home/.cache/pip
-  #     CACHE_DIR: /home/.cache
-  #     TASK: formers-fleet-CI-${{ github.event.pull_request.number }}-integration-test-multi-card
-  #   steps:
-  #     - name: Check docker image and run container
-  #       run: |
-  #         container_name=${TASK}-$(date +%Y%m%d-%H%M%S)
-  #         echo "container_name=${container_name}" >> ${{ github.env }}
-  #         docker pull $docker_image
-  #         docker run -d -t --name ${container_name} --gpus all --shm-size=32G \
-  #           -v "/dev/shm:/dev/shm"  \
-  #           -v ${{ github.workspace }}/../../..:${{ github.workspace }}/../../.. \
-  #           -v ${{ github.workspace }}/../../..:/root \
-  #           -v /ssd1/paddle-1/action_cache:/home/.cache \
-  #           -v ${{ github.workspace }}:/workspace \
-  #           -e BRANCH \
-  #           -e PR_ID \
-  #           -e COMMIT_ID \
-  #           -e PADDLE_ROOT \
-  #           -e ci_scripts \
-  #           -e CACHE_DIR \
-  #           -e no_proxy \
-  #           -e CI_name \
-  #           -e PIP_CACHE_DIR \
-  #           -e GITHUB_SHA="${{ github.event.pull_request.head.sha }}" \
-  #           -e GITHUB_HEAD_REF="${{ github.head_ref }}" \
-  #           -e GITHUB_BASE_SHA="${{ github.event.pull_request.base.sha }}" \
-  #           -e GITHUB_REPO_NAME="${{ github.repository }}" \
-  #           -e GITHUB_EVENT_NAME="${{ github.event_name }}" \
-  #           -e GITHUB_EVENT_PULL_REQUEST_NUMBER="${{ github.event.pull_request.number }}" \
-  #           -e GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
-  #           -e GITHUB_RUN_ID="${{ github.run_id }}" \
-  #           -e PR_USER="${{ github.event.pull_request.user.login }}" \
-  #           -w /workspace --network host ${docker_image}
+  integration-test-H20-multi-card:
+    needs: check_documents_type
+    if: ${{ needs.check_documents_type.outputs.is_md_only == 'false' }}
+    name: Integration test (H20, multi-card)
+    runs-on:
+      group: Fleet-H-multi-card
+    env:
+      PIP_CACHE_DIR: /home/.cache/pip
+      CACHE_DIR: /home/.cache
+      TASK: formers-fleet-CI-${{ github.event.pull_request.number }}-integration-test-multi-card
+    steps:
+      - name: Check docker image and run container
+        run: |
+          container_name=${TASK}-$(date +%Y%m%d-%H%M%S)
+          echo "container_name=${container_name}" >> ${{ github.env }}
+          docker pull $docker_image
+          docker run -d -t --name ${container_name} --gpus all --shm-size=32G \
+            -v "/dev/shm:/dev/shm"  \
+            -v ${{ github.workspace }}/../../..:${{ github.workspace }}/../../.. \
+            -v ${{ github.workspace }}/../../..:/root \
+            -v /ssd1/paddle-1/action_cache:/home/.cache \
+            -v ${{ github.workspace }}:/workspace \
+            -e BRANCH \
+            -e PR_ID \
+            -e COMMIT_ID \
+            -e PADDLE_ROOT \
+            -e ci_scripts \
+            -e CACHE_DIR \
+            -e no_proxy \
+            -e CI_name \
+            -e PIP_CACHE_DIR \
+            -e GITHUB_SHA="${{ github.event.pull_request.head.sha }}" \
+            -e GITHUB_HEAD_REF="${{ github.head_ref }}" \
+            -e GITHUB_BASE_SHA="${{ github.event.pull_request.base.sha }}" \
+            -e GITHUB_REPO_NAME="${{ github.repository }}" \
+            -e GITHUB_EVENT_NAME="${{ github.event_name }}" \
+            -e GITHUB_EVENT_PULL_REQUEST_NUMBER="${{ github.event.pull_request.number }}" \
+            -e GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
+            -e GITHUB_RUN_ID="${{ github.run_id }}" \
+            -e PR_USER="${{ github.event.pull_request.user.login }}" \
+            -w /workspace --network host ${docker_image}
 
       - name: Install PaddleFormers
         id: formers_install
@@ -455,44 +455,44 @@ jobs:
   #         timeout 5m bash -x PaddleFormers/tests/integration_test/qwen.sh lora
   #         '
 
-  #     - name: Qwen vl sft
-  #       if: (success() || failure()) && steps.formers_install.conclusion == 'success'
-  #       run: |
-  #         docker exec -t ${{ env.container_name }} /bin/bash -ce '
-  #         source /root/proxy
-  #         timeout 5m bash -x PaddleFormers/tests/integration_test/qwen3vl_sft.sh tp8 h20
+      - name: Qwen vl sft
+        if: (success() || failure()) && steps.formers_install.conclusion == 'success'
+        run: |
+          docker exec -t ${{ env.container_name }} /bin/bash -ce '
+          source /root/proxy
+          timeout 5m bash -x PaddleFormers/tests/integration_test/qwen3vl_sft.sh tp8 h20
       
-  #     - name: Qwen vl lora
-  #       if: (success() || failure()) && steps.formers_install.conclusion == 'success'
-  #       run: |
-  #         docker exec -t ${{ env.container_name }} /bin/bash -ce '
-  #         source /root/proxy
-  #         timeout 5m bash -x PaddleFormers/tests/integration_test/qwen3vl_lora.sh h20
-  #         '
-  #         '
+      - name: Qwen vl lora
+        if: (success() || failure()) && steps.formers_install.conclusion == 'success'
+        run: |
+          docker exec -t ${{ env.container_name }} /bin/bash -ce '
+          source /root/proxy
+          timeout 5m bash -x PaddleFormers/tests/integration_test/qwen3vl_lora.sh h20
+          '
+          '
 
-  #     - name: Qwen vl moe
-  #       if: (success() || failure()) && steps.formers_install.conclusion == 'success'
-  #       run: |
-  #         docker exec -t ${{ env.container_name }} /bin/bash -ce '
-  #         source /root/proxy
-  #         timeout 10m bash -x PaddleFormers/tests/integration_test/qwen3vl_sft.sh moe h20
-  #         '
+      - name: Qwen vl moe
+        if: (success() || failure()) && steps.formers_install.conclusion == 'success'
+        run: |
+          docker exec -t ${{ env.container_name }} /bin/bash -ce '
+          source /root/proxy
+          timeout 10m bash -x PaddleFormers/tests/integration_test/qwen3vl_sft.sh moe h20
+          '
       
-  #     - name: Qwen3-vl-8k-fsdp
-  #       if: (success() || failure()) && steps.formers_install.conclusion == 'success'
-  #       run: |
-  #         docker exec -t ${{ env.container_name }} /bin/bash -ce '
-  #         source /root/proxy
-  #         timeout 10m bash -x PaddleFormers/tests/integration_test/qwen3vl_sft.sh fsdp h20
-  #         '
+      - name: Qwen3-vl-8k-fsdp
+        if: (success() || failure()) && steps.formers_install.conclusion == 'success'
+        run: |
+          docker exec -t ${{ env.container_name }} /bin/bash -ce '
+          source /root/proxy
+          timeout 10m bash -x PaddleFormers/tests/integration_test/qwen3vl_sft.sh fsdp h20
+          '
 
-  #     - name: Terminate and delete the container
-  #       if: ${{ always() }}
-  #       run: |
-  #         set +e
-  #         docker exec -t ${{ env.container_name }} /bin/bash -c 'rm -rf * .[^.]*'
-  #         docker rm -f ${{ env.container_name }}
+      - name: Terminate and delete the container
+        if: ${{ always() }}
+        run: |
+          set +e
+          docker exec -t ${{ env.container_name }} /bin/bash -c 'rm -rf * .[^.]*'
+          docker rm -f ${{ env.container_name }}
       
 
   integration-test-a100:
