test

diff --git a/.github/workflows/fleet-model-test.yml b/.github/workflows/fleet-model-test.yml
--- a/.github/workflows/fleet-model-test.yml
+++ b/.github/workflows/fleet-model-test.yml
@@ -311,40 +311,40 @@ jobs:
           bash -x PaddleFormers/tests/integration_test/qwen.sh pt
           glm45_exit_code=$?
           if [[ "$glm45_exit_code" != "0" ]]; then
-            echo -e "::error:: \033[31mIntegration test failed: GLM4.5.\033[0m"
+            echo -e "::error:: \033[31mIntegration test failed: Qwen pre-train.\033[0m"
             exit 1
           else
-            echo -e "\033[32mIntegration test succeeded: GLM4.5 FP8.\033[0m"
+            echo -e "\033[32mIntegration test succeeded: Qwen pre-train.\033[0m"
           fi
           '
         
       - name: Qwen sft
-        if: (success() || failure()) && steps.formers_install.conclusion == 'success'
+        # if: (success() || failure()) && steps.formers_install.conclusion == 'success'
         run: |
           docker exec -t ${{ env.container_name }} /bin/bash -ce '
           source /root/proxy
           bash -x PaddleFormers/tests/integration_test/qwen.sh sft
           glm45_exit_code=$?
           if [[ "$glm45_exit_code" != "0" ]]; then
-            echo -e "::error:: \033[31mIntegration test failed: GLM4.5.\033[0m"
+            echo -e "::error:: \033[31mIntegration test failed: Qwen sft.\033[0m"
             exit 1
           else
-            echo -e "\033[32mIntegration test succeeded: GLM4.5 FP8.\033[0m"
+            echo -e "\033[32mIntegration test succeeded: Qwen sft.\033[0m"
           fi
           '
 
       - name: Qwen lora
-        if: (success() || failure()) && steps.formers_install.conclusion == 'success'
+        # if: (success() || failure()) && steps.formers_install.conclusion == 'success'
         run: |
           docker exec -t ${{ env.container_name }} /bin/bash -ce '
           source /root/proxy
           bash -x PaddleFormers/tests/integration_test/qwen.sh lora
           glm45_exit_code=$?
           if [[ "$glm45_exit_code" != "0" ]]; then
-            echo -e "::error:: \033[31mIntegration test failed: GLM4.5.\033[0m"
+            echo -e "::error:: \033[31mIntegration test failed: Qwen lora.\033[0m"
             exit 1
           else
-            echo -e "\033[32mIntegration test succeeded: GLM4.5 FP8.\033[0m"
+            echo -e "\033[32mIntegration test succeeded: Qwen lora.\033[0m"
           fi
           '
 
