add multi glm45 cli cases

diff --git a/.github/workflows/fleet-model-test.yml b/.github/workflows/fleet-model-test.yml
--- a/.github/workflows/fleet-model-test.yml
+++ b/.github/workflows/fleet-model-test.yml
@@ -18,7 +18,7 @@ env:
   PADDLE_ROOT: /paddle
   ci_scripts: /paddle/ci
   BRANCH: ${{ github.event.pull_request.base.ref || github.ref_name }}
-  CI_name: formers_test
+  CI_name: fleet-model-test
   no_proxy: "bcebos.com,.bcebos.com,apiin.im.baidu.com,gitee.com,aliyun.com,.baidu.com,.tuna.tsinghua.edu.cn"
   docker_image: "ccr-2vdh3abv-pub.cnc.bj.baidubce.com/paddlepaddle/paddle:cuda129-coverage-test"
 
@@ -27,155 +27,6 @@ defaults:
     shell: bash
 
 jobs:
-  integration-test-H20-single-card:
-    name: Integration test (H20, single card)
-    runs-on:
-      group: Fleet-H-single-card
-    env:
-      PIP_CACHE_DIR: /root/.cache/pip
-      CACHE_DIR: /root/.cache
-      TASK: formers-fleet-CI-${{ github.event.pull_request.number }}-integration-test-single-card
-    steps:
-      - name: Determine the runner
-        run: |
-          gpu_id=$(( $(echo $PWD | awk -F'/' '{print $3}' | awk -F'-' '{print $2}') + 3 ))
-          echo GPU_DEVICES="$gpu_id" >> $GITHUB_ENV
-
-      - name: Check docker image and run container
-        env:
-          GPU_DEVICES: ${{ env.GPU_DEVICES }}
-        run: |
-          container_name=${TASK}-$(date +%Y%m%d-%H%M%S)
-          echo "container_name=${container_name}" >> ${{ github.env }}
-          docker pull $docker_image
-          set -x
-          docker run -d -t --name ${container_name} --gpus "\"device=${GPU_DEVICES}\"" --shm-size=32G \
-            -v "/dev/shm:/dev/shm"  \
-            -v ${{ github.workspace }}/../../..:${{ github.workspace }}/../../.. \
-            -v ${{ github.workspace }}/../../../proxy:/root/proxy \
-            -v /ssd1/paddle-1/action_cache:/root/.cache \
-            -v ${{ github.workspace }}:/workspace \
-            -e BRANCH \
-            -e PR_ID \
-            -e COMMIT_ID \
-            -e work_dir \
-            -e PADDLE_ROOT \
-            -e ci_scripts \
-            -e CACHE_DIR \
-            -e no_proxy \
-            -e CI_name \
-            -e PIP_CACHE_DIR \
-            -e GITHUB_SHA="${{ github.event.pull_request.head.sha }}" \
-            -e GITHUB_HEAD_REF="${{ github.head_ref }}" \
-            -e GITHUB_BASE_SHA="${{ github.event.pull_request.base.sha }}" \
-            -e GITHUB_REPO_NAME="${{ github.repository }}" \
-            -e GITHUB_EVENT_NAME="${{ github.event_name }}" \
-            -e GITHUB_EVENT_PULL_REQUEST_NUMBER="${{ github.event.pull_request.number }}" \
-            -e GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
-            -e GITHUB_RUN_ID="${{ github.run_id }}" \
-            -w /workspace --network host ${docker_image}
-
-      - name: Install PaddleFleet
-        run: |
-          docker exec -t ${{ env.container_name }} /bin/bash -ce '
-          nvidia-smi
-          rm -rf * .[^.]*
-          source /root/proxy
-          export UV_LOCK_TIMEOUT=600
-          git clone https://github.com/PaddlePaddle/PaddleFleet.git
-          cd PaddleFleet
-          git log -1
-          git config --global --add safe.directory /workspace/PaddleFleet
-          git config user.name "PaddleCI"
-          git config user.email "paddle_ci@example.com"
-          git config pull.rebase false
-          mkdir -p /root/.cache/pip
-          pip cache dir
-          pip install --upgrade pip
-          echo "Install uv"
-          pip install uv
-          echo "uv sync"
-          uv sync --group ci -v > /dev/null
-          export UV_SKIP_WHEEL_FILENAME_CHECK=1
-          uv pip install https://paddle-qa.bj.bcebos.com/paddle-pipeline/Develop-GpuAll-LinuxCentos-Gcc11-Cuda129-Cudnn99-Trt105-Py310-Compile/latest/paddlepaddle_gpu-0.0.0-cp310-cp310-linux_x86_64.whl --index-url=https://www.paddlepaddle.org.cn/packages/nightly/cu129/ --force-reinstall
-          cat > /tmp/check_paddle.py << 'EOF'
-          import paddle
-          print("paddle_commit:", paddle.version.commit)
-          EOF
-          source ../PaddleFleet/.venv/bin/activate
-          python /tmp/check_paddle.py
-          '
-
-      - name: Install PaddleFormers
-        id: formers_install
-        run: |
-          docker exec -t ${{ env.container_name }} /bin/bash -ce '
-          source /root/proxy
-          git clone https://github.com/PaddlePaddle/PaddleFormers.git
-          cd PaddleFormers
-          git config --global --add safe.directory /workspace/PaddleFormers
-          git config user.name "PaddleCI"
-          git config user.email "paddle_ci@example.com"
-          git config pull.rebase false
-          git pull --no-edit origin pull/${PR_ID}/head
-          sed -i "s/from gpt_provider import GPTModelProvider/from paddleformers.transformers.gpt_provider import GPTModelProvider/g" examples/experiments/paddlefleet/glm45_provider.py
-          sed -i "s/from gpt_provider import GPTModelProvider/from paddleformers.transformers.gpt_provider import GPTModelProvider/g" examples/experiments/paddlefleet/qwen_provider.py
-          source ../PaddleFleet/.venv/bin/activate
-          pip install -e .
-          '
-
-      - name: Proprocess for integration test
-        if: (success() || failure()) && steps.formers_install.conclusion == 'success'
-        run: |
-          docker exec -t ${{ env.container_name }} /bin/bash -ce '
-          source /root/proxy
-          bash -x PaddleFleet/ci/integration_test/preprocess.sh
-          preprocess_exit_code=$?
-          if [[ "$preprocess_exit_code" != "0" ]]; then
-            echo -e "::error:: \033[31mPreprocess failed.\033[0m"
-            exit 1
-          else
-            echo -e "\033[32mPreprocess succeeded.\033[0m"
-          fi
-          '
-
-      - name: Integration test (GLM4.5 single-card)
-        if: (success() || failure()) && steps.formers_install.conclusion == 'success'
-        run: |
-          docker exec -t ${{ env.container_name }} /bin/bash -ce '
-          source /root/proxy
-          bash -x PaddleFleet/ci/integration_test/glm45_single_card.sh
-          glm45_single_card_exit_code=$?
-          if [[ "$glm45_single_card_exit_code" != "0" ]]; then
-            echo -e "::error:: \033[31mIntegration test failed: GLM4.5 single-card.\033[0m"
-            exit 1
-          else
-            echo -e "\033[32mIntegration test succeeded: GLM4.5 single-card.\033[0m"
-          fi
-          '
-
-      - name: Integration test (Qwen3-30B-A3B single-card)
-        if: (success() || failure()) && steps.formers_install.conclusion == 'success'
-        run: |
-          docker exec -t ${{ env.container_name }} /bin/bash -ce '
-          source /root/proxy
-          bash -x PaddleFleet/ci/integration_test/qwen3_single_card.sh
-          qwen3_single_card_exit_code=$?
-          if [[ "$qwen3_single_card_exit_code" != "0" ]]; then
-            echo -e "::error:: \033[31mIntegration test failed: Qwen3-30B-A3B single-card.\033[0m"
-            exit 1
-          else
-            echo -e "\033[32mIntegration test succeeded: Qwen3-30B-A3B single-card.\033[0m"
-          fi
-          '
-
-      - name: Terminate and delete the container
-        if: ${{ always() }}
-        run: |
-          set +e
-          docker exec -t ${{ env.container_name }} /bin/bash -c 'rm -rf * .[^.]*'
-          docker rm -f ${{ env.container_name }}
-
   integration-test-H20-multi-card:
     name: Integration test (H20, multi-card)
     runs-on:
@@ -198,7 +49,6 @@ jobs:
             -v ${{ github.workspace }}:/workspace \
             -e BRANCH \
             -e PR_ID \
-            -e work_dir \
             -e COMMIT_ID \
             -e PADDLE_ROOT \
             -e ci_scripts \
@@ -221,7 +71,6 @@ jobs:
           docker exec -t ${{ env.container_name }} /bin/bash -ce '
           rm -rf * .[^.]*
           source /root/proxy
-          export UV_LOCK_TIMEOUT=600
           git clone https://github.com/PaddlePaddle/PaddleFleet.git
           cd PaddleFleet
           git config --global --add safe.directory /workspace/PaddleFleet
@@ -234,15 +83,12 @@ jobs:
           echo "Install uv"
           pip install uv
           echo "uv sync"
+          git submodule update --init --recursive
           uv sync --group ci -v > /dev/null
           export UV_SKIP_WHEEL_FILENAME_CHECK=1
           uv pip install https://paddle-qa.bj.bcebos.com/paddle-pipeline/Develop-GpuAll-LinuxCentos-Gcc11-Cuda129-Cudnn99-Trt105-Py310-Compile/latest/paddlepaddle_gpu-0.0.0-cp310-cp310-linux_x86_64.whl --index-url=https://www.paddlepaddle.org.cn/packages/nightly/cu129/ --force-reinstall
-          cat > /tmp/check_paddle.py << 'EOF'
-          import paddle
-          print("paddle_commit:", paddle.version.commit)
-          EOF
-          source ../PaddleFleet/.venv/bin/activate
-          python /tmp/check_paddle.py
+          source .venv/bin/activate
+          python -c "import paddle; print(paddle.version.commit)"
           '
 
       - name: Install PaddleFormers
@@ -252,28 +98,16 @@ jobs:
           source /root/proxy
           git clone https://github.com/PaddlePaddle/PaddleFormers.git
           cd PaddleFormers
+          cp examples/experiments/paddlefleet/glm45.json examples/experiments/paddlefleet/glm45_fp8.json
           git config --global --add safe.directory /workspace/PaddleFormers
           git config user.name "PaddleCI"
           git config user.email "paddle_ci@example.com"
           git config pull.rebase false
+          git pull --no-edit origin pull/3200/head
           git pull --no-edit origin pull/${PR_ID}/head
           source ../PaddleFleet/.venv/bin/activate
           pip install -e .
-          '
-
-      - name: Proprocess for integration test
-        if: (success() || failure()) && steps.formers_install.conclusion == 'success'
-        run: |
-          docker exec -t ${{ env.container_name }} /bin/bash -ce '
-          source /root/proxy
-          bash -x PaddleFleet/ci/integration_test/preprocess.sh
-          preprocess_exit_code=$?
-          if [[ "$preprocess_exit_code" != "0" ]]; then
-            echo -e "::error:: \033[31mPreprocess failed.\033[0m"
-            exit 1
-          else
-            echo -e "\033[32mPreprocess succeeded.\033[0m"
-          fi
+          python -c "import paddle; print(paddle.version.commit)"
           '
 
       - name: Integration test (GLM4.5 multi-card)
@@ -282,6 +116,23 @@ jobs:
           docker exec -t ${{ env.container_name }} /bin/bash -ce '
           source /root/proxy
           bash -x PaddleFleet/ci/integration_test/glm45.sh
+          glm45_exit_code=$?
+          ls -a /workspace/PaddleFleet/coveragedata-multi
+          source /workspace/PaddleFleet/.venv/bin/activate
+          if [[ "$glm45_exit_code" != "0" ]]; then
+            echo -e "::error:: \033[31mIntegration test failed: GLM4.5.\033[0m"
+            exit 1
+          else
+            echo -e "\033[32mIntegration test succeeded: GLM4.5.\033[0m"
+          fi
+          '
+
+      - name: Integration test (GLM4.5 multi-card FP8)
+        if: (success() || failure()) && steps.formers_install.conclusion == 'success'
+        run: |
+          docker exec -t ${{ env.container_name }} /bin/bash -ce '
+          source /root/proxy
+          bash -x PaddleFleet/ci/integration_test/glm45_fp8.sh
           glm45_exit_code=$?
           if [[ "$glm45_exit_code" != "0" ]]; then
             echo -e "::error:: \033[31mIntegration test failed: GLM4.5.\033[0m"
@@ -321,7 +172,6 @@ jobs:
             -e BRANCH \
             -e PR_ID \
             -e COMMIT_ID \
-            -e work_dir \
             -e PADDLE_ROOT \
             -e ci_scripts \
             -e CACHE_DIR \
@@ -355,9 +205,12 @@ jobs:
           echo "Install uv"
           pip install uv
           echo "uv sync"
+          git submodule update --init --recursive
           uv sync --group ci > /dev/null
           export UV_SKIP_WHEEL_FILENAME_CHECK=1
-          uv pip install https://paddle-qa.bj.bcebos.com/paddle-pipeline/Develop-GpuAll-LinuxCentos-Gcc11-Cuda129-Cudnn99-Trt105-Py310-Compile/latest/paddlepaddle_gpu-0.0.0-cp310-cp310-linux_x86_64.whl --index-url=https://www.paddlepaddle.org.cn/packages/nightly/cu129/
+          uv pip install https://paddle-qa.bj.bcebos.com/paddle-pipeline/Develop-GpuAll-LinuxCentos-Gcc11-Cuda129-Cudnn99-Trt105-Py310-Compile/latest/paddlepaddle_gpu-0.0.0-cp310-cp310-linux_x86_64.whl --index-url=https://www.paddlepaddle.org.cn/packages/nightly/cu129/ --force-reinstall
+          source .venv/bin/activate
+          python -c "import paddle; print(paddle.version.commit)"
           '
 
       - name: Install PaddleFormers
@@ -370,23 +223,11 @@ jobs:
           git config user.name "PaddleCI"
           git config user.email "paddle_ci@example.com"
           git config pull.rebase false
+          git pull --no-edit origin pull/3200/head
           git pull --no-edit origin pull/${PR_ID}/head
           source ../PaddleFleet/.venv/bin/activate
           pip install -e .
-          '
-
-      - name: Proprocess for integration test
-        run: |
-          docker exec -t ${{ env.container_name }} /bin/bash -ce '
-          source /root/proxy
-          bash -x PaddleFleet/ci/integration_test/preprocess.sh
-          preprocess_exit_code=$?
-          if [[ "$preprocess_exit_code" != "0" ]]; then
-            echo -e "::error:: \033[31mPreprocess failed.\033[0m"
-            exit 1
-          else
-            echo -e "\033[32mPreprocess succeeded.\033[0m"
-          fi
+          python -c "import paddle; print(paddle.version.commit)"
           '
 
       - name: Integration test (GLM4.5)
@@ -409,3 +250,4 @@ jobs:
           set +e
           docker exec -t ${{ env.container_name }} /bin/bash -c 'rm -rf * .[^.]*'
           docker rm -f ${{ env.container_name }}
+
