fix error and add error deal

diff --git a/.github/workflows/fleet-model-test.yml b/.github/workflows/fleet-model-test.yml
--- a/.github/workflows/fleet-model-test.yml
+++ b/.github/workflows/fleet-model-test.yml
@@ -115,13 +115,19 @@ jobs:
         run: |
           docker exec -t ${{ env.container_name }} /bin/bash -ce '
           source /root/proxy
-          bash -x PaddleFleet/ci/integration_test/glm45.sh
+          bash -x PaddleFleet/ci/integration_test/glm45.sh | tee glm45.log
           glm45_exit_code=$?
-          ls -a /workspace/PaddleFleet/coveragedata-multi
           source /workspace/PaddleFleet/.venv/bin/activate
           if [[ "$glm45_exit_code" != "0" ]]; then
-            echo -e "::error:: \033[31mIntegration test failed: GLM4.5.\033[0m"
-            exit 1
+            echo -e "Integration test failed: GLM4.5, try to analyze log."
+            python PaddleFleet/ci/check_log_for_exitcode.py glm45.log integration true
+            find_error_exit_code=$?
+            if [[ "$find_error_exit_code" != "0" ]]; then
+              echo -e "::error:: \033[31mIntegration test failed: GLM4.5.\033[0m"
+            else
+              echo -e "\033[32mIntegration test succeeded: GLM4.5.\033[0m"
+            fi
+            exit $find_error_exit_code
           else
             echo -e "\033[32mIntegration test succeeded: GLM4.5.\033[0m"
           fi
@@ -132,11 +138,18 @@ jobs:
         run: |
           docker exec -t ${{ env.container_name }} /bin/bash -ce '
           source /root/proxy
-          bash -x PaddleFleet/ci/integration_test/glm45_fp8.sh
+          bash -x PaddleFleet/ci/integration_test/glm45_fp8.sh | tee glm45_fp8.log
           glm45_exit_code=$?
           if [[ "$glm45_exit_code" != "0" ]]; then
-            echo -e "::error:: \033[31mIntegration test failed: GLM4.5.\033[0m"
-            exit 1
+            echo -e "Integration test failed: GLM4.5, try to analyze log."
+            python PaddleFleet/ci/check_log_for_exitcode.py glm45_fp8.log integration true
+            find_error_exit_code=$?
+            if [[ "$find_error_exit_code" != "0" ]]; then
+              echo -e "::error:: \033[31mIntegration test failed: GLM4.5 FP8.\033[0m"
+            else
+              echo -e "\033[32mIntegration test succeeded: GLM4.5.\033[0m"
+            fi
+            exit $find_error_exit_code
           else
             echo -e "\033[32mIntegration test succeeded: GLM4.5.\033[0m"
           fi
@@ -234,11 +247,18 @@ jobs:
         run: |
           docker exec -t ${{ env.container_name }} /bin/bash -ce '
           source /root/proxy
-          bash -x PaddleFleet/ci/integration_test/glm45_a100.sh
+          bash -x PaddleFleet/ci/integration_test/glm45_a100.sh | tee glm45_a100.log
           glm45_exit_code=$?
           if [[ "$glm45_exit_code" != "0" ]]; then
-            echo -e "::error:: \033[31mIntegration test failed: GLM4.5.\033[0m"
-            exit 1
+            echo -e "Integration test failed: GLM4.5, try to analyze log."
+            python PaddleFleet/ci/check_log_for_exitcode.py glm45_a100.log integration false
+            find_error_exit_code=$?
+            if [[ "$find_error_exit_code" != "0" ]]; then
+              echo -e "::error:: \033[31mIntegration test failed: GLM4.5.\033[0m"
+            else
+              echo -e "\033[32mLog analysis did not find specific errors.\033[0m"
+            fi
+            exit $find_error_exit_code
           else
             echo -e "\033[32mIntegration test succeeded: GLM4.5.\033[0m"
           fi
